// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// read_ibdData
Rcpp::List read_ibdData(Rcpp::CharacterVector file, bool header, char sep, char quote, bool rowNames, int nPos, Rcpp::CharacterVector na_str, int nrows);
RcppExport SEXP _AMPRIL_read_ibdData(SEXP fileSEXP, SEXP headerSEXP, SEXP sepSEXP, SEXP quoteSEXP, SEXP rowNamesSEXP, SEXP nPosSEXP, SEXP na_strSEXP, SEXP nrowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type file(fileSEXP);
    Rcpp::traits::input_parameter< bool >::type header(headerSEXP);
    Rcpp::traits::input_parameter< char >::type sep(sepSEXP);
    Rcpp::traits::input_parameter< char >::type quote(quoteSEXP);
    Rcpp::traits::input_parameter< bool >::type rowNames(rowNamesSEXP);
    Rcpp::traits::input_parameter< int >::type nPos(nPosSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type na_str(na_strSEXP);
    Rcpp::traits::input_parameter< int >::type nrows(nrowsSEXP);
    rcpp_result_gen = Rcpp::wrap(read_ibdData(file, header, sep, quote, rowNames, nPos, na_str, nrows));
    return rcpp_result_gen;
END_RCPP
}
// chiSqTables
List chiSqTables(RawVector x1, RawVector x2, CharacterVector labels);
RcppExport SEXP _AMPRIL_chiSqTables(SEXP x1SEXP, SEXP x2SEXP, SEXP labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< RawVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type labels(labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(chiSqTables(x1, x2, labels));
    return rcpp_result_gen;
END_RCPP
}
// similarityIBD
NumericMatrix similarityIBD(RawMatrix x, NumericVector pWeight, CharacterVector labels);
RcppExport SEXP _AMPRIL_similarityIBD(SEXP xSEXP, SEXP pWeightSEXP, SEXP labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RawMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pWeight(pWeightSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type labels(labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(similarityIBD(x, pWeight, labels));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AMPRIL_read_ibdData", (DL_FUNC) &_AMPRIL_read_ibdData, 8},
    {"_AMPRIL_chiSqTables", (DL_FUNC) &_AMPRIL_chiSqTables, 3},
    {"_AMPRIL_similarityIBD", (DL_FUNC) &_AMPRIL_similarityIBD, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_AMPRIL(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
