# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chiSqTables <- function(x1, x2, labels) {
    .Call('AMPRIL_chiSqTables', PACKAGE = 'AMPRIL', x1, x2, labels)
}

read_ibdData <- function(file, header, sep, quote, rowNames, nPos, na_str, nrows) {
    .Call('AMPRIL_read_ibdData', PACKAGE = 'AMPRIL', file, header, sep, quote, rowNames, nPos, na_str, nrows)
}

