# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_ibdData <- function(file, header, sep, quote, rowNames, nPos, na_str, nrows) {
    .Call('_AMPRIL_read_ibdData', PACKAGE = 'AMPRIL', file, header, sep, quote, rowNames, nPos, na_str, nrows)
}

chiSqTables <- function(x1, x2, labels) {
    .Call('_AMPRIL_chiSqTables', PACKAGE = 'AMPRIL', x1, x2, labels)
}

similarityIBD <- function(x, pWeight, labels) {
    .Call('_AMPRIL_similarityIBD', PACKAGE = 'AMPRIL', x, pWeight, labels)
}

